# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
 repositories:
   - repository: pipelines-java
     type: github
     name: SruthiKorembathe/pipelines-java
     endpoint: github.com_SruthiKorembathe



trigger:
- none

pool: default

stages:
- stage: different repo
  jobs:
  - job: building
    steps:
    - task: NuGetCommand@2
      inputs:
       command: 'push'
       packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
       nuGetFeedType: 'internal'
    - template: templates/stage-job-step.yml
    